database: bot.db
default_timeout: 60
checkpoints:
  - name: Brest
    id: a9173a85-3fc0-424c-84f0-defa632481e4
  - name: Berestovica
    id: 7e46a2d1-ab2f-11ec-bafb-ac1f6bf889c1
  - name: Bruzgi
    id: 3b797d4d-706a-440f-a1a4-826c191e1e36
